### ISSUE TITLE
[Q] stable branch/tag and `docker-compose.yml` file?

### ISSUE THREAD

**Issue by hiroyuki-sato** [CenterForOpenScience/osf.io#10681]
Hello, team. I'm new to this project.

## Overview

I would like to run OSF.io for connecting and test some services (S3 compatible storage/cloud service, etc)
(It means I don't develop OSF.io itself yet.)

## Problem.

I'm following [Docker and OS Setup](https://github.com/CenterForOpenScience/osf.io/blob/develop/README-docker-compose.md#application-runtime) steps.
When I execute `docker-compose up requirements mfr_requirements wb_requirements gv_requirements` in 24.04.3 tag (84bc6c5278fcf4ab574bc0c45aa30aff3263d247), `mfr_requirements` exit with status code 1.

The problem seems to be a mismatch of Python versions between the `docker-compose.yml` and `quay.io/centerforopenscience/mfr:develop` images.
(Please see [error.txt](https://github.com/user-attachments/files/16301044/error.txt))

| File/Image   | Python |
|-------------|--------|
|  quay.io/centerforopenscience/mfr:develop | python 3.6 |
|  mfr_requirements  docker-compose.yml | python 3.5 |

```yaml
  #########################
  # Modular File Renderer #
  #########################

  mfr_requirements:
    image: quay.io/centerforopenscience/mfr:develop
    command:
      - /bin/bash
      - -c
      - invoke install --develop &&
        (python -m compileall /usr/local/lib/python3.5 || true) &&
        rm -Rf /python3.5/* &&
        cp -Rf -p /usr/local/lib/python3.5 /
    restart: 'no'
    volumes:
      - mfr_requirements_vol:/python3.5
      - mfr_requirements_local_bin_vol:/usr/local/bin
```

```
% docker run -it quay.io/centerforopenscience/mfr:develop /bin/bash
root@20b42877e9af:/code# python --version
Python 3.6.15
```

```
mfr_requirements-1  |   Running setup.py bdist_wheel for waterbutler ... done
mfr_requirements-1  |   Stored in directory: /tmp/pip-ephem-wheel-cache-f662xak6/wheels/f5/07/45/e5cb9895e6ea16ae2a5c9a32d078229a3e9709f9ea38fdfcc2
mfr_requirements-1  | Successfully built waterbutler
mfr_requirements-1  | Installing collected packages: waterbutler
mfr_requirements-1  |   Found existing installation: waterbutler 0.38.6
mfr_requirements-1  |     Uninstalling waterbutler-0.38.6:
mfr_requirements-1  |       Successfully uninstalled waterbutler-0.38.6
mfr_requirements-1  | Successfully installed waterbutler-0.38.6
mfr_requirements-1  | You are using pip version 18.1, however version 21.3.1 is available.
mfr_requirements-1  | You should consider upgrading via the 'pip install --upgrade pip' command.
mfr_requirements-1  | Listing '/usr/local/lib/python3.5'...
mfr_requirements-1  | Can't list '/usr/local/lib/python3.5'
mfr_requirements-1  | cp: cannot stat '/usr/local/lib/python3.5': No such file or directory
mfr_requirements-1 exited with code 1
```

## Questions

* What branch/tag should I use to test OSF.io? (not develop, I want to use the stable version)? Is the `24.04.3` stable tag?
* Can I get the stable `docker-compose.yml` file? (Not development tag, stable tag, or specific hash ID)

## Environment

* Docker: Docker version 27.0.3, build 7d4bcd8
* Docker Compose version v2.29.0
* OSF.io: 84bc6c5278fcf4ab574bc0c45aa30aff3263d247 (`24.04.3` tag)
* Ubuntu 22.04
